version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: test
    volumes:
      - db:/data/db
      - configdb:/data/configdb
      - ./database/:/docker-entrypoint-initdb.d/

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017/

  app:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - ./app/:/workspace/app/:ro
    environment:
      - DB_USERNAME
      - DB_PASSWORD
    working_dir: /workspace/
    command: npm start

  sso:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 3001:3001
    volumes:
      - ./testing/:/workspace/testing/:ro
    environment:
      - DB_USERNAME
      - DB_PASSWORD
    working_dir: /workspace/
    command: npm test

volumes:
  db:
  configdb:
